{{- if .Values.prometheus.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "abs-support.fullname" . }}
  labels:
    {{- include "abs-support.labels" . | nindent 4 }}
spec:
  endpoints:
  - port: {{ .Values.prometheus.port | default "http" }}
    path: {{ .Values.prometheus.path | default "/prometheus" }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace}}
  selector:
    matchLabels:
      {{- include "abs-support.selectorLabels" . | nindent 6 }}
{{- end }}
